"""
Domain entities — core business objects with identity.

These are plain Python dataclasses / classes that belong in the domain
layer.  They know nothing about FastAPI, SQLAlchemy, or any framework.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from decimal import Decimal
from uuid import UUID, uuid4


@dataclass
class FinancialReport:
    """A financial report generated by the copilot."""

    id: UUID = field(default_factory=uuid4)
    title: str = ""
    report_type: str = ""  # "balance_sheet", "income", "cashflow", "custom"
    company_id: str = ""
    period_start: datetime | None = None
    period_end: datetime | None = None
    content: str = ""
    metadata: dict | None = None
    created_at: datetime = field(default_factory=datetime.utcnow)
    updated_at: datetime = field(default_factory=datetime.utcnow)


@dataclass
class AnalysisRequest:
    """An AI-powered analysis request submitted by a user."""

    id: UUID = field(default_factory=uuid4)
    user_id: str = ""
    query: str = ""
    context: dict | None = None
    status: str = "pending"  # pending, processing, completed, failed
    result: str = ""
    created_at: datetime = field(default_factory=datetime.utcnow)
    completed_at: datetime | None = None


@dataclass
class MarketSnapshot:
    """Point-in-time snapshot of a financial instrument."""

    symbol: str
    price: Decimal
    change: Decimal
    change_percent: Decimal
    volume: int
    timestamp: datetime = field(default_factory=datetime.utcnow)
    source: str = ""
